#!/usr/bin/with-contenv /bin/sh
set -e

# Ensure mail domain is set.
if [ "$DOMAIN" = "" ]; then
    echo "Error: \$DOMAIN is a required environment variable."
    exit 1
fi

# Sender mapping
echo -n '' > /etc/postfix/sender_canonical_maps
IFS=,; for uname in `echo "$ALLOWED_SENDERS" | sed -r 's/@[^,]+//g'`; do echo "/${uname}@/ ${uname}@${DOMAIN}" >> /etc/postfix/sender_canonical_maps; done
echo "/(.*)@.*/ no-reply@${DOMAIN}" >> /etc/postfix/sender_canonical_maps

# Configure headers
echo "/^X-Mailer:/ IGNORE" > /etc/postfix/smtp_header_checks
echo "/Subject:\s*(.*)/ REPLACE Subject: ${SUBJECT_PREPEND}\$1${SUBJECT_APPEND}" >> /etc/postfix/smtp_header_checks

# Configure relaying
if [ "$RELAY_ENABLED" = true ]; then
    postconf -e relayhost="[${RELAY_HOST}]:${RELAY_PORT}"
    echo "[${RELAY_HOST}]:${RELAY_PORT} ${RELAY_LOGIN}:${RELAY_PASSWORD}" > /etc/postfix/sasl_password
else
    postconf -e relayhost=""
    echo -n "" > /etc/postfix/sasl_password
fi

# Format allowed recipients
echo -n '' > /etc/postfix/transport_maps
if [ "$ALLOWED_RECIPIENTS" != "" ]; then
    echo -n "${ALLOWED_RECIPIENTS},* discard:recipient not in list of allowed recipients" | sed 's/,/ :\n/g' > /etc/postfix/transport_maps
fi

# Index files
newaliases
postmap /etc/postfix/sasl_password
postmap /etc/postfix/transport_maps

# Start postfix.
postfix start
trap "exit 0" SIGTERM
trap "exit 0" SIGHUP
trap "exit 0" SIGINT

# Wait until postfix is killed.
while kill -0 "$(cat /var/spool/postfix/pid/master.pid | tr -d [:space:])"; do
    usleep 250000
done
